### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#387] opened 2019-12-30 16:32 UTC
The link http://www.elexis.info is dead. Also the links to the repositories (e.g. http://download.elexis.info/3.7/p2/target) are dead.

**Comment by col-panic** [comment] 2019-12-30 18:06
Not sure what the problem is here http://download.elexis.info/elexis/3.7/ works .. don't know about www.elexis.info

**Comment by ngiger** [comment] 2020-01-07 09:20
Fixed with systemctl start jekyll. Don't know yet why it stopped.

**Comment by col-panic** [comment] 2020-01-07 09:22
I did an esxi upgrade and rebooted the machine - could you please change syscfg such that is automatically starts on reboot? thanks

**Comment by ngiger** [comment] 2020-01-07 09:29
Done with systemctl enable jekyll.

**Comment by col-panic** [comment] 2020-01-07 09:30
thx

**Comment by ngiger** [comment] 2020-01-07 09:30
Please reboot the machine again and check aftertwards. If everything is okay I am in favor to close this issue.

**Closed by col-panic** 2020-01-07 09:30 UTC
